const state={photos:[],scanComplete:false};
setTimeout(()=>document.getElementById('splash').classList.add('hide'),1200);
document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active-screen'));document.getElementById(btn.dataset.screen).classList.add('active-screen');}));
document.getElementById('scanBtn').addEventListener('click',runScan);
function runScan(){let p=0;const bar=document.getElementById('progressBar'),status=document.getElementById('scanStatus');status.textContent='Scanning storage, photos and device signals...';const timer=setInterval(()=>{p+=Math.floor(Math.random()*14)+6;if(p>=100){p=100;clearInterval(timer);state.scanComplete=true;status.textContent='Scan complete. Lumero found optimisation opportunities.';document.getElementById('healthScore').textContent='87';document.getElementById('healthText').textContent='Good condition. Photo review and screenshot cleanup would improve storage efficiency.';document.getElementById('clutterScore').textContent='58';}bar.style.width=p+'%';},260)}
document.getElementById('photoInput').addEventListener('change',async e=>{const files=[...e.target.files].filter(f=>f.type.startsWith('image/'));for(const file of files){const dataUrl=await readFile(file);const score=await sharpnessScore(dataUrl);state.photos.push({name:file.name,size:file.size,dataUrl,score});}renderPhotos();document.getElementById('photoCount').textContent=state.photos.length;});
function readFile(file){return new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file);});}
function sharpnessScore(src){return new Promise(resolve=>{const img=new Image();img.onload=()=>{const canvas=document.getElementById('analysisCanvas');const max=220;const scale=Math.min(max/img.width,max/img.height,1);canvas.width=Math.max(1,Math.floor(img.width*scale));canvas.height=Math.max(1,Math.floor(img.height*scale));const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,canvas.width,canvas.height);const d=ctx.getImageData(0,0,canvas.width,canvas.height).data;let sum=0,count=0;for(let y=1;y<canvas.height-1;y+=2){for(let x=1;x<canvas.width-1;x+=2){const i=(y*canvas.width+x)*4;const c=.299*d[i]+.587*d[i+1]+.114*d[i+2];const ix=(y*canvas.width+x+1)*4;const iy=((y+1)*canvas.width+x)*4;const cx=.299*d[ix]+.587*d[ix+1]+.114*d[ix+2];const cy=.299*d[iy]+.587*d[iy+1]+.114*d[iy+2];sum+=Math.abs(c-cx)+Math.abs(c-cy);count++;}}resolve(Math.round(Math.min(100,Math.max(1,(sum/count)*1.7))));};img.src=src;});}
function renderPhotos(){const wrap=document.getElementById('photoResults');wrap.innerHTML='';state.photos.forEach(p=>{const status=p.score>55?'Sharp / likely keeper':p.score>30?'Review': 'Likely blurry';const el=document.createElement('article');el.className='photo-card';el.innerHTML=`<img src="${p.dataUrl}" alt="${p.name}"><div><span class="badge">Score ${p.score}/100</span><h3>${p.name}</h3><p>${status}</p><p>${(p.size/1024/1024).toFixed(2)} MB</p></div>`;wrap.appendChild(el);});}
document.getElementById('reportBtn').addEventListener('click',()=>{const total=state.photos.reduce((a,p)=>a+p.size,0);const best=[...state.photos].sort((a,b)=>b.score-a.score)[0];document.getElementById('reportOutput').textContent=`Lumero v0.2 Session Report\n\nPhotos analysed: ${state.photos.length}\nApprox uploaded size: ${(total/1024/1024).toFixed(2)} MB\nBest shot candidate: ${best?best.name+' — score '+best.score+'/100':'No images analysed yet'}\nScan status: ${state.scanComplete?'Completed':'Not run yet'}\n\nPrivacy note: This prototype analyses selected files locally in your browser. No uploads are performed.`;});
document.getElementById('cleanBtn').addEventListener('click',()=>{const amount=(2.4+Math.random()*13).toFixed(1);document.getElementById('recoveryAmount').textContent=amount+' GB potential';});
document.getElementById('bestShotBtn').addEventListener('click',()=>{const out=document.getElementById('bestShotResult');if(!state.photos.length){out.innerHTML='<h3>Best Shot Intelligence</h3><p>Upload photos first.</p>';return;}const best=[...state.photos].sort((a,b)=>b.score-a.score)[0];out.innerHTML=`<h3>Best Shot Candidate</h3><p>Lumero recommends <strong>${best.name}</strong> with a sharpness score of <strong>${best.score}/100</strong>.</p><img src="${best.dataUrl}" style="max-width:260px;border-radius:18px;border:1px solid rgba(120,170,255,.25)">`;});
